#!/bin/sh

if [ -f log ]; then
	rm log || exit 1
fi


if [ ! -d mplayer ]; then
	echo -e "\e[1m*** Checking out mplayer\e[0m"
	svn -q co svn://svn.mplayerhq.hu/mplayer/trunk mplayer || exit 1
fi

cd mplayer

echo -e "\e[1m*** Updating mplayer\e[0m"
svn up || exit 1

echo

	
if [ ! -d ffmpeg ]; then
	echo -e "\e[1m*** Checking out FFMPEG\e[0m"
	git clone --depth 1 git://source.ffmpeg.org/ffmpeg.git ffmpeg || exit 1
else
	echo -e "\e[1m*** Updating FFMPEG\e[0m"
	pushd ffmpeg >/dev/null
	git pull || exit 1
	popd >/dev/null
fi

./configure --help > ../b.options
	
ln -s config.log ../config.log

echo
echo -e "\e[1m*** Configuring mplayer\e[0m"
./configure \
	--extra-ldflags="-L/usr/local/lib -L/usr/lib64/nvidia -L/usr/lib64" \
	--extra-libs="-laacplus -lavcodec -lavdevice -lavfilter -lavformat -lavresample -lavutil -lmjpegutils -lpostproc -lswresample -lswscale -lvo-aacenc -lx264" \
	--language=en \
	--enable-{xv,vdpau,xvmc,gl,sdl} \
	--disable-{dvdnav,vcd,ftp,tv,networking,cddb,smb,dvb,v4l2,tga,pnm,mng,unrarexec,libdv} \
	--with-vidix-drivers=nvidia \
	--disable-{real,xanim,lib{gsm,opus,openjpeg,dca}} \
	--disable-ffmpeg_{a,so} \
	--disable-{dvdread,{dvdread,libdvdcss}-internal} \
	--disable-{dvdread,libdvdcss}-internal \
	--disable-{fbdev,caca,aa,directfb,fbdev} \
	--disable-xss \
	--enable-lirc \
	--enable-fastmemcpy \
	--enable-rpath \
	--enable-hardcoded-tables \
	--with-xvmclib=XvMCNVIDIA \
	--enable-encoder={aac,ac3,ac3fixed,dvvideo,libaacplus,libfaac,libmp3lame,libvo_aacenc,libx264,libx264rgb,libxvid,mpeg4,msmpeg4v2,msmpeg4v3,pcm_s16le} \
	--enable-demuxer={aac,ac3,asf,avi,dts,dv,flac,flv,h263,h264,m4v,matroska,mp3,mpegps,mpegts,mpegvideo,vqf,wav} \
	--enable-muxer={aac,ac3,asf,avi,dts,dv,flac,flv,h263,h264,m4v,matroska,mp3,mpegps,mpegts,mpegvideo,vqf,wav} \
	--enable-parser={aac,aac_latm,flac,h263,h264,mpeg4video,mpegaudio,mpegvideo} \
>../log 2>&1 || exit 1
	
echo
echo -e "\e[1mCleaning mplayer\e[0m"
make clean >/dev/null

echo
echo -e "\e[1mCompiling tablegen\e[0m"
pushd ffmpeg/libavcodec	>/dev/null
for i in `ls *_tablegen.c`; do
	gcc -c -o tmp.o "$i" -DCONFIG_SMALL=0 -I.. || exit 1
	gcc -o tmp tmp.o -lm || exit 1
	mv tmp.o "${i%.c}.o"
	mv tmp "${i%.c}"
done
popd >/dev/null

echo
echo -e "\e[1mBuilding mplayer\e[0m"
sleep 1

make -j5 || exit 1

echo
echo -e "\e[1mInstalling mplayer\e[0m"
sleep 1

make install || exit 1

echo
echo -e "\e[1mCleaning mplayer\e[0m"
make clean	

echo
echo -e "\e[1mDONE!\e[0m"
